### ISSUE TITLE
RSS feed broken

### ISSUE THREAD

**Issue by Guite** [zikula/zikula.org#28]
http://zikula.org/forums/feed does not work, because the theme output is included.

**Comment by craigh** [comment]
should this be in the dizkus project then?

**Comment by Guite** [comment]
I wasn't sure about it, since it could be that zikula.org has done some customisation.

**Comment by craigh** [comment]
please reopen at the dizkus project. I am pretty certain there are no customizations.

**Comment by Guite** [comment]
Done here: https://github.com/zikula-modules/DizkusModule/issues/275
