### ISSUE TITLE
Support tags for extensions list

### ISSUE THREAD

**Issue by Guite** [zikula/zikula.org#33]
On the download page extensions are currently just listed without any categorisation.
We could utilise the GitHub tags for repositories in order to introduce filters.
Examples:
- community
- content management
- security
- tested for Core x.y.
- needs help
- ...

**Comment by Kaik** [comment]
I'm still thinking about it but some random thoughts:
- Only released! I think there is no point to display unreleased ones...
- can we read composer.json?
- supported version

**Comment by Guite** [comment]
> Only released! I think there is no point to display unreleased ones...
I think this would be possible. Don't remember correctly, but I believe that release information is available in the data fetched from GitHub.

> can we read composer.json?
Not really, because we can not assume that the module's main directory is placed in the repository's root folder.
