### ISSUE TITLE
Improve inclusion of YouTube videos

### ISSUE THREAD

**Issue by Guite** [zikula/zikula.org#36]
On the documentation page there is a list of YouTube videos embedded which is based on the keyword _Zikula_. It is not clear though that this is a list of multiple videos. The user needs to open the selection list in the upper left corner of the video player.
We need to find a better way for this. Including a real list of single videos (each in a separate row) seems only possible based on a playlist. We want to have a keyword though to have the dynamical results without having to maintain the playlist explicitly.

**Comment by Kaik** [comment]
I think playlist should be maintained... it might be easier if admin/moderator on one side has displayed the playlist and by keyword list, on other, I know Zikula is not a popular keyword but you know the Internet is wild someone will hack it just for fun...

**Comment by Guite** [comment]
I understand your point, but who wants to maintain it (not once, but regularly and for a long time)?

**Comment by Kaik** [comment]
Well, there is not a big problem when the list is not up to date (there are new videos that are not listed), but there will be a problem when a stupid/unrelated video is shown on the list automatically...
When you search yt for zikula this shows up as 5th result  https://www.youtube.com/watch?v=kEkZZrQaxWk and then every few "our Zikula" vids there is one with a guy and his cattle ;)

**Comment by Guite** [comment]
Again: I understand your point, but who wants to maintain it?

**Comment by Guite** [comment]
Asked in Slack for a volunteer.

**Comment by craigh** [comment]
https://developers.google.com/youtube/v3/sample_requests

scroll down to the “Search” example

**Comment by Guite** [comment]
It is now based on a playlist so only "whitelisted" videos are included.
Display is still the same as before.

We could utilise something like http://woosterwebdesign.com/responsive-youtube-player-with-playlist/ but I wonder whether this might be over-engineered.

**Comment by Guite** [comment]
Now we have a separate playlist for German videos. The separate installation video has been removed as it is contained in the playlist, too. Next I will check out how to improve the display in order to finish this issue.

**Comment by Guite** [comment]
Revamped video display is now available :smile:
