### ISSUE TITLE
Videos don't play

### ISSUE THREAD

**Issue by craigh** [zikula/zikula.org#38]
![Screen Shot 2019-10-31 at 6 57 55 AM](https://user-images.githubusercontent.com/350048/67941335-c97e7c80-fbab-11e9-991f-3bfd952a4a06.png)
All the videos on the documentation page look like this. The buttons do not operate, so the videos don't play.

**Comment by Guite** [comment]
Thanks for reporting! I am aware of this problem. Have filed a ticket at the provider for it.

**Comment by Guite** [comment]
It's now working like expected.

**Comment by craigh** [comment]
confirmed. thank you
